- name: Provision AWS EC2 Instances with VPC and Subnet
  hosts: localhost
  gather_facts: no
  vars_files:
    - ec2_2_vars.yml
  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        state: present
      register: vpc

    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
      register: igw

    - name: Create Public Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr }}"
        az: "{{ aws_region }}a"
        map_public: yes
        state: present
        region: "{{ aws_region }}"
      register: subnet

    - name: Create Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
      register: route_table

    - name: Associate Route Table with Subnet
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        state: present
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: rt_association

    - name: Create Security Group
      amazon.aws.ec2_group:
        name: "{{ security_group }}"
        description: "Security group for EC2 instances"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 5000
            to_port: 5000
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 9000
            to_port: 9000
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 5173
            to_port: 5173
            cidr_ip: 0.0.0.0/0
      register: sg

    - name: Launch EC2 Instances
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        security_groups: ["{{ sg.group_id }}"]
        wait: yes
        count: 1
        tags:
          Name: "webapp-instance-{{ item }}"
      with_sequence: start=1 end=3
      register: ec2_instances

    - name: Add new instances to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groups: ec2_hosts
      loop: "{{ ec2_instances.instances }}"

    - name: Debug Information
      debug:
        msg: "Created instance with ID: {{ item.id }}, Public IP: {{ item.public_ip }}, Name: webapp-instance-{{ loop.index }}"
      loop: "{{ ec2_instances.instances }}"